version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings:DefaultConnection=${CONNECTIONSTRINGS_DEFAULTCONNECTION}
      - ConnectionStrings:IdentityConnection=${CONNECTIONSTRINGS_IDENTITYCONNECTION}
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT}
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - dockerapi-dev